name = "paperless-sender"
main = "src/worker.ts"
compatibility_date = "2024-10-26"
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1

[vars]
IGNORED_MIME_TYPES = "application/pgp-keys,application/pgp-signature"
