// Generated by Wrangler by running `wrangler types ./src/worker-configuration.d.ts`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
	CF_ACCESS_CLIENT_ID: string;
	CF_ACCESS_CLIENT_SECRET: string;
	PAPERLESS_TOKEN: string;
	PAPERLESS_API_BASE: string;
	POSTMASTER_EMAIL: string;
	PAPERLESS_DEFAULT_TAG?: string;
	PAPERLESS_FORCED_TAG?: string;
	IGNORED_MIME_TYPES?: string;
}
